import { z } from "zod";
import { isPlayableJobId, isStarterJobId } from "../domain/jobs.js";
export const selectStarterJobSchema = z.object({ jobId: z.string().refine(isStarterJobId) }).strict();
export const switchJobSchema = z.object({ jobId: z.string().refine(isPlayableJobId) }).strict();
export const battleStartSchema = z.object({ nodeId: z.string().regex(/^map[1-4]\.[a-z0-9_]+$/), presetId: z.string().uuid().optional(), idempotencyKey: z.string().uuid() }).strict();
export const battleAckSchema = z.object({ battleId: z.string().uuid() }).strict();
export const autosaveSchema = z.object({ version:z.number().int().nonnegative(), idempotencyKey:z.string().uuid(), changes:z.object({ tutorialFlags:z.record(z.string(),z.boolean()).optional(), settings:z.object({ language:z.enum(["th","en"]).optional(), autoRepeat:z.boolean().optional(), autoUseScroll:z.boolean().optional() }).strict().optional() }).strict() }).strict();
export const equipItemSchema=z.object({itemDbId:z.string().uuid()}).strict();
export const unequipItemSchema=z.object({slot:z.enum(["weapon","helmet","armor","pants","shoes","gloves"])}).strict();
export const enhanceItemSchema=z.object({itemDbId:z.string().uuid(),idempotencyKey:z.string().uuid()}).strict();
export const allocateStatsSchema=z.object({str:z.number().int().nonnegative().max(500),dex:z.number().int().nonnegative().max(500),con:z.number().int().nonnegative().max(500),int:z.number().int().nonnegative().max(500)}).strict();
export const slotCardSchema=z.object({slotNo:z.number().int().min(1).max(6),cardId:z.string().min(1).max(96),rarity:z.enum(["common","uncommon","rare","epic","legendary"])}).strict();
export const unslotCardSchema=z.object({slotNo:z.number().int().min(1).max(6)}).strict();
export const mergeCardSchema=z.object({cardId:z.string().min(1).max(96),rarity:z.enum(["common","uncommon","rare","epic"]),idempotencyKey:z.string().uuid()}).strict();
