import { Mulberry32 } from "./prng.js";
import type { SkillDefinition } from "../data/skills.js";
import type { BattleEvent,BattleResult,BattleSetup,CombatUnitSetup } from "./types.js";
const GAUGE_MAX=1000,SPD_MIN=20;
interface RuntimeUnit { readonly setup:CombatUnitSetup; hp:number; gauge:number; readonly cooldowns:Map<string,number>; }
function validateSetup(setup:BattleSetup):void{if(!Number.isInteger(setup.tickLimit)||setup.tickLimit<=0)throw new RangeError("tickLimit must be a positive integer.");if(setup.units.length<2)throw new RangeError("A battle requires at least two units.");const ids=new Set<string>();for(const unit of setup.units){if(ids.has(unit.id))throw new Error(`Duplicate unit id: ${unit.id}`);ids.add(unit.id);if(unit.stats.maxHp<=0||unit.stats.spd<=0)throw new RangeError(`Invalid stats for unit ${unit.id}.`);}}
function enemies(actor:RuntimeUnit,units:readonly RuntimeUnit[]):RuntimeUnit[]{return units.filter(x=>x.hp>0&&x.setup.side!==actor.setup.side);}
function allies(actor:RuntimeUnit,units:readonly RuntimeUnit[]):RuntimeUnit[]{return units.filter(x=>x.hp>0&&x.setup.side===actor.setup.side);}
function lowestHp(list:readonly RuntimeUnit[]):RuntimeUnit|undefined{return [...list].sort((a,b)=>(a.hp/a.setup.stats.maxHp)-(b.hp/b.setup.stats.maxHp)||a.setup.id.localeCompare(b.setup.id))[0];}
function targetFor(skill:SkillDefinition,actor:RuntimeUnit,units:readonly RuntimeUnit[]):RuntimeUnit|undefined{switch(skill.targeting){case"self":return actor;case"lowestHpAlly":return lowestHp(allies(actor,units));case"highestAtkEnemy":return [...enemies(actor,units)].sort((a,b)=>Math.max(b.setup.stats.patk,b.setup.stats.matK)-Math.max(a.setup.stats.patk,a.setup.stats.matK))[0];default:return lowestHp(enemies(actor,units));}}
function conditionPasses(skill:SkillDefinition,actor:RuntimeUnit,units:readonly RuntimeUnit[]):boolean{const c=skill.condition;switch(c.kind){case"always":return true;case"targetCountAtLeast":return enemies(actor,units).length>=c.value;case"selfHpAtMost":return actor.hp/actor.setup.stats.maxHp*100<=c.value;case"allyHpAtMost":return allies(actor,units).some(x=>x.hp/x.setup.stats.maxHp*100<=c.value);}}
function chooseSkill(actor:RuntimeUnit,units:readonly RuntimeUnit[]):SkillDefinition|undefined{return actor.setup.prioritySkills?.find(skill=>skill.executableInSprint&&(actor.cooldowns.get(skill.id)??0)<=0&&conditionPasses(skill,actor,units)&&targetFor(skill,actor,units));}
function checksum(result:Omit<BattleResult,"checksum">):string{const input=JSON.stringify(result);let hash=0x811c9dc5;for(let i=0;i<input.length;i++){hash^=input.charCodeAt(i);hash=Math.imul(hash,0x01000193);}return(hash>>>0).toString(16).padStart(8,"0");}
export function simulateBattle(setup:BattleSetup):BattleResult{validateSetup(setup);const random=new Mulberry32(setup.seed);const units:RuntimeUnit[]=setup.units.map(setup=>({setup,hp:setup.stats.maxHp,gauge:0,cooldowns:new Map()}));const events:BattleEvent[]=[];const alive=(side:"player"|"enemy")=>units.some(x=>x.setup.side===side&&x.hp>0);
for(let tick=1;tick<=setup.tickLimit;tick++){for(const unit of units){if(unit.hp<=0)continue;unit.gauge+=Math.max(SPD_MIN,Math.floor(unit.setup.stats.spd));for(const [id,value] of unit.cooldowns)unit.cooldowns.set(id,Math.max(0,value-1));}
const ready=units.filter(x=>x.hp>0&&x.gauge>=GAUGE_MAX).sort((a,b)=>b.gauge-a.gauge||b.setup.stats.spd-a.setup.stats.spd||(random.nextFloat()<.5?-1:1));
for(const actor of ready){if(actor.hp<=0)continue;actor.gauge-=GAUGE_MAX;const skill=chooseSkill(actor,units);const target=skill?targetFor(skill,actor,units):lowestHp(enemies(actor,units));if(!target)continue;
if(skill){events.push({tick,type:"skill_cast",actorId:actor.setup.id,targetId:target.setup.id,skillId:skill.id});actor.cooldowns.set(skill.id,skill.cooldownTicks);}else events.push({tick,type:"normal_attack",actorId:actor.setup.id,targetId:target.setup.id});
if(skill?.school==="heal"){const power=actor.setup.stats[skill.governingStat];const amount=Math.max(1,Math.floor(power*skill.multiplier*(.95+random.nextFloat()*.1)));target.hp=Math.min(target.setup.stats.maxHp,target.hp+amount);events.push({tick,type:"heal",actorId:actor.setup.id,targetId:target.setup.id,skillId:skill.id,amount});continue;}
const hitChance=Math.min(100,Math.max(50,90+(actor.setup.stats.hit-target.setup.stats.flee)*.5));if(random.nextFloat()*100>=hitChance){events.push(skill?{tick,type:"miss",actorId:actor.setup.id,targetId:target.setup.id,skillId:skill.id}:{tick,type:"miss",actorId:actor.setup.id,targetId:target.setup.id});continue;}
const attack=skill?actor.setup.stats[skill.governingStat]:actor.setup.stats.patk;const multiplier=skill?.multiplier??1;const mitigated=attack*multiplier*(100/(100+Math.max(0,target.setup.stats.def)));const variance=.95+random.nextFloat()*.1;const critical=random.nextFloat()*100<actor.setup.stats.critRate;const damage=Math.max(1,Math.floor(mitigated*variance*(critical?actor.setup.stats.critDamage/100:1)));target.hp=Math.max(0,target.hp-damage);events.push(skill?{tick,type:"damage",actorId:actor.setup.id,targetId:target.setup.id,skillId:skill.id,amount:damage,critical}:{tick,type:"damage",actorId:actor.setup.id,targetId:target.setup.id,amount:damage,critical});if(target.hp===0)events.push(skill?{tick,type:"death",actorId:actor.setup.id,targetId:target.setup.id,skillId:skill.id}:{tick,type:"death",actorId:actor.setup.id,targetId:target.setup.id});
const playerAlive=alive("player"),enemyAlive=alive("enemy");if(!playerAlive||!enemyAlive){const partial={outcome:playerAlive?"victory":"defeat",ticksElapsed:tick,events,remainingHp:Object.fromEntries(units.map(x=>[x.setup.id,x.hp]))} as const;return{...partial,checksum:checksum(partial)};}}
}
const partial={outcome:"timeout",ticksElapsed:setup.tickLimit,events,remainingHp:Object.fromEntries(units.map(x=>[x.setup.id,x.hp]))} as const;return{...partial,checksum:checksum(partial)};}
