import { useEffect, useMemo, useState } from "react";
import { CARDS, ENHANCEMENT_COSTS, ITEMS, type ItemRarity, type ProgressionResponse } from "@loce/shared";
import { api } from "../api/client.js";

type Tab="equipment"|"cards"|"stats";
const rarityName:Record<ItemRarity,string>={common:"Common",uncommon:"Uncommon",rare:"Rare",epic:"Epic",legendary:"Legendary"};
const key=()=>crypto.randomUUID();
export function ProgressionScreen({onBack}:{onBack:()=>void}):React.JSX.Element{
 const [data,setData]=useState<ProgressionResponse|null>(null);const [tab,setTab]=useState<Tab>("equipment");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const load=async()=>setData(await api.request<ProgressionResponse>("/progression"));
 useEffect(()=>{void load();},[]);
 const equipped=useMemo(()=>new Map((data?.items??[]).filter(x=>x.equippedSlot).map(x=>[x.equippedSlot!,x])),[data]);
 async function act(path:string,body:unknown):Promise<void>{setBusy(true);setMessage("");try{await api.request(path,{method:"POST",body:JSON.stringify(body)});await load();setMessage("บันทึกสำเร็จ");}catch{setMessage("ทำรายการไม่สำเร็จ กรุณาลองอีกครั้ง");}finally{setBusy(false);}}
 if(!data)return <main className="screen"><div className="loading">กำลังโหลดข้อมูลตัวละคร...</div></main>;
 return <main className="progression-screen"><header className="panel-header"><button onClick={onBack}>← กลับเมือง</button><h1>Character Progression</h1><strong>Gold {data.gold.toLocaleString()}</strong></header><nav className="tab-bar"><button onClick={()=>setTab("equipment")}>อุปกรณ์</button><button onClick={()=>setTab("cards")}>การ์ด</button><button onClick={()=>setTab("stats")}>ค่าสถานะ</button></nav>{message&&<p className="status-message">{message}</p>}
 {tab==="equipment"&&<section className="progress-grid"><article className="parchment"><h2>Equipped</h2>{(["weapon","helmet","armor","pants","shoes","gloves"] as const).map(slot=>{const item=equipped.get(slot);return <div className="slot-row" key={slot}><strong>{slot}</strong><span>{item?`${ITEMS[item.itemId]?.name??item.itemId} +${item.enhanceLevel}`:"ว่าง"}</span>{item&&<button disabled={busy} onClick={()=>void act("/items/unequip",{slot})}>ถอด</button>}</div>;})}</article><article className="parchment"><h2>Inventory {data.items.length}/{data.inventoryCap}</h2>{data.items.map(item=><div className="inventory-row" key={item.id}><div><strong>{ITEMS[item.itemId]?.name??item.itemId}</strong><small>{rarityName[item.rarity]} · +{item.enhanceLevel}{item.equippedSlot?` · ${item.equippedSlot}`:""}</small></div><button disabled={busy} onClick={()=>void act("/items/equip",{itemDbId:item.id})}>ใส่</button><button disabled={busy||item.enhanceLevel>=10} onClick={()=>void act("/items/enhance",{itemDbId:item.id,idempotencyKey:key()})}>ตีบวก ({item.enhanceLevel<10?ENHANCEMENT_COSTS[item.enhanceLevel+1]:"MAX"}g)</button></div>)}</article></section>}
 {tab==="cards"&&<section className="progress-grid"><article className="parchment"><h2>Card Slots</h2>{[1,2,3,4,5,6].map(slot=>{const card=data.cards.find(x=>x.slotNo===slot);return <div className="slot-row" key={slot}><strong>Slot {slot}</strong><span>{card?`${CARDS[card.cardId]?.name??card.cardId} (${rarityName[card.rarity]})`:"ว่าง"}</span>{card&&<button disabled={busy} onClick={()=>void act("/cards/unslot",{slotNo:slot})}>ถอด</button>}</div>;})}</article><article className="parchment"><h2>Card Album</h2>{data.cards.map(card=><div className="inventory-row" key={`${card.cardId}:${card.rarity}`}><div><strong>{CARDS[card.cardId]?.name??card.cardId}</strong><small>{rarityName[card.rarity]} · จำนวน {card.qty}{card.slotNo?` · Slot ${card.slotNo}`:""}</small></div><select disabled={busy} defaultValue="" onChange={e=>{const slot=Number(e.target.value);if(slot)void act("/cards/slot",{slotNo:slot,cardId:card.cardId,rarity:card.rarity});}}><option value="">ใส่ช่อง...</option>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>Slot {n}</option>)}</select><button disabled={busy||card.qty<3||card.rarity==="legendary"} onClick={()=>void act("/cards/merge",{cardId:card.cardId,rarity:card.rarity,idempotencyKey:key()})}>รวม 3 ใบ</button></div>)}</article></section>}
 {tab==="stats"&&<StatEditor data={data} busy={busy} onSave={input=>act("/jobs/allocate",input)}/>}</main>;
}
function StatEditor({data,busy,onSave}:{data:ProgressionResponse;busy:boolean;onSave:(x:{str:number;dex:number;con:number;int:number})=>Promise<void>}):React.JSX.Element{
 const [stats,setStats]=useState(data.activeJob.stats);const total=stats.str+stats.dex+stats.con+stats.int;const allowed=4*(data.activeJob.level-1);const remaining=allowed-total;
 const field=(name:keyof typeof stats)=><label className="stat-field"><span>{name.toUpperCase()}</span><input type="number" min={0} max={500} value={stats[name]} onChange={e=>setStats({...stats,[name]:Math.max(0,Number(e.target.value)||0)})}/></label>;
 return <section className="parchment stat-panel"><h2>{data.activeJob.jobId} Lv.{data.activeJob.level}</h2><p>แต้มทั้งหมด {allowed} · คงเหลือ {remaining}</p><div className="stat-grid">{field("str")}{field("dex")}{field("con")}{field("int")}</div><button disabled={busy||remaining<0} onClick={()=>void onSave(stats)}>ยืนยันการจัดสรร</button></section>;
}
