import type { JobTreeNode, MapNodeSummary, PlayableJobId } from "@loce/shared";
import { useEffect, useState } from "react";
import { api } from "../api/client.js";
import type { Bootstrap, JobTreeResponse } from "../app/types.js";
import { MapScreen } from "./MapScreen.js";
import { BattleScreen } from "./BattleScreen.js";
import { ProgressionScreen } from "./ProgressionScreen.js";
import { SkillBuilderScreen } from "./SkillBuilderScreen.js";
const names:Record<string,string>={swordman:"Swordman",mage:"Mage",archer:"Archer",healer:"Healer",magic_knight:"Magic Knight",paladin:"Paladin",dragoon:"Dragoon",spell_archer:"Spell Archer",sage:"Sage",bard:"Bard"};
export function TownScreen({bootstrap,onRefresh,onLogout}:{bootstrap:Bootstrap;onRefresh:()=>void;onLogout:()=>void}):React.JSX.Element{
 const [tree,setTree]=useState<readonly JobTreeNode[]>([]);const [open,setOpen]=useState(false);const [screen,setScreen]=useState<"town"|"map"|"battle"|"progression"|"skills">("town");const [node,setNode]=useState<MapNodeSummary|null>(null);
 useEffect(()=>{void api.request<JobTreeResponse>("/jobs/tree").then((x)=>setTree(x.nodes));},[]);
 async function switchJob(jobId:PlayableJobId):Promise<void>{await api.request("/jobs/switch",{method:"POST",body:JSON.stringify({jobId})});onRefresh();}
 if(screen==="progression")return <ProgressionScreen onBack={()=>{setScreen("town");onRefresh();}}/>;
 if(screen==="skills")return <SkillBuilderScreen onBack={()=>setScreen("town")}/>;
 if(screen==="map")return <MapScreen onBack={()=>setScreen("town")} onSelect={(selected)=>{setNode(selected);setScreen("battle");}}/>;
 if(screen==="battle"&&node)return <BattleScreen node={node} onExit={()=>{setNode(null);setScreen("town");onRefresh();}}/>;
 return <main className="town"><header className="topbar"><div><strong>{bootstrap.displayName}</strong><span>อาชีพ: {bootstrap.currentJobId?names[bootstrap.currentJobId]:"-"}</span></div><button className="text-button light" onClick={onLogout}>ออกจากระบบ</button></header><section className="town-scene"><div className="town-title"><h1>Riverdale</h1><p>เมืองเริ่มต้น — เขตปลอดภัยสำหรับสลับอาชีพและจัด Build</p></div><button className="npc job-master" onClick={()=>setOpen(true)}><span>🧙</span>Job Master</button><button className="npc battle-gate" onClick={()=>setScreen("map")}><span>🗺️</span>ออกผจญภัย</button><div className="player-token">{bootstrap.currentJobId?.slice(0,1).toUpperCase()}</div></section><nav className="bottom-nav"><button onClick={()=>setOpen(true)}>ต้นไม้อาชีพ</button><button onClick={()=>setScreen("map")}>ต่อสู้</button><button onClick={()=>setScreen("progression")}>ตัวละคร / กระเป๋า</button><button onClick={()=>setScreen("skills")}>สกิล</button></nav>{open&&<div className="modal-backdrop"><section className="parchment job-tree"><button className="close" onClick={()=>setOpen(false)}>×</button><h2>ต้นไม้อาชีพ</h2><p>Tier 2 และ Tier 3 ซ่อนเป็นเงาพร้อมคำใบ้จนกว่าจะปลดล็อก</p>{[1,2,3].map((tier)=><div key={tier} className="tier-row"><h3>Tier {tier}</h3><div className="tree-grid">{tree.filter((n)=>n.tier===tier).map((item)=><article key={item.id} className={item.displayMode==="silhouette"?"tree-node silhouette":"tree-node"}><div className="portrait">{item.displayMode==="silhouette"?"?":names[item.id]}</div><strong>{item.displayMode==="silhouette"?"อาชีพลับ":names[item.id]}</strong>{item.hintKey&&<small>คำใบ้: เส้นทางวิวัฒนาการยังไม่ถูกเปิดเผย</small>}{item.unlocked&&item.playable&&item.id!==bootstrap.currentJobId&&<button className="secondary" onClick={()=>void switchJob(item.id as PlayableJobId)}>สลับอาชีพ</button>}{item.id===bootstrap.currentJobId&&<span className="active-badge">ใช้งานอยู่</span>}{!item.playable&&<span className="future-badge">ยังไม่เปิดใน Test Build</span>}</article>)}</div></div>)}</section></div>}</main>;
}
