import type { JobTreeNode, PlayableJobId } from "@loce/shared";
import { useEffect, useState } from "react";
import { api } from "../api/client.js";
import type { Bootstrap, JobTreeResponse } from "../app/types.js";
const names: Record<string, string> = { swordman: "Swordman", mage: "Mage", archer: "Archer", healer: "Healer", magic_knight: "Magic Knight", paladin: "Paladin", dragoon: "Dragoon", spell_archer: "Spell Archer", sage: "Sage", bard: "Bard" };
export function TownScreen({ bootstrap, onRefresh, onLogout }: { bootstrap: Bootstrap; onRefresh: () => void; onLogout: () => void }): React.JSX.Element {
 const [tree, setTree] = useState<readonly JobTreeNode[]>([]); const [open, setOpen] = useState(true);
 useEffect(() => { void api.request<JobTreeResponse>("/jobs/tree").then((x) => setTree(x.nodes)); }, []);
 async function switchJob(jobId: PlayableJobId): Promise<void> { await api.request("/jobs/switch", { method: "POST", body: JSON.stringify({ jobId }) }); onRefresh(); }
 return <main className="town"><header className="topbar"><div><strong>{bootstrap.displayName}</strong><span>อาชีพ: {bootstrap.currentJobId ? names[bootstrap.currentJobId] : "-"}</span></div><button className="text-button light" onClick={onLogout}>ออกจากระบบ</button></header><section className="town-scene"><div className="town-title"><h1>Riverdale</h1><p>เมืองเริ่มต้น — เขตปลอดภัยสำหรับสลับอาชีพและจัด Build</p></div><button className="npc job-master" onClick={() => setOpen(true)}><span>🧙</span>Job Master</button><div className="player-token">{bootstrap.currentJobId?.slice(0, 1).toUpperCase()}</div></section><nav className="bottom-nav"><button onClick={() => setOpen(true)}>ต้นไม้อาชีพ</button><button disabled>ต่อสู้ (M2)</button><button disabled>กระเป๋า (M2)</button><button disabled>สกิล (M2)</button></nav>{open && <div className="modal-backdrop"><section className="parchment job-tree"><button className="close" onClick={() => setOpen(false)}>×</button><h2>ต้นไม้อาชีพ</h2><p>อาชีพ Tier 2 และ Tier 3 จะซ่อนเป็นเงาพร้อมคำใบ้จนกว่าจะปลดล็อก</p>{[1,2,3].map((tier) => <div key={tier} className="tier-row"><h3>Tier {tier}</h3><div className="tree-grid">{tree.filter((n) => n.tier === tier).map((node) => <article key={node.id} className={node.displayMode === "silhouette" ? "tree-node silhouette" : "tree-node"}><div className="portrait">{node.displayMode === "silhouette" ? "?" : names[node.id]}</div><strong>{node.displayMode === "silhouette" ? "อาชีพลับ" : names[node.id]}</strong>{node.hintKey && <small>คำใบ้: เส้นทางวิวัฒนาการยังไม่ถูกเปิดเผย</small>}{node.unlocked && node.playable && node.id !== bootstrap.currentJobId && <button className="secondary" onClick={() => void switchJob(node.id as PlayableJobId)}>สลับอาชีพ</button>}{node.id === bootstrap.currentJobId && <span className="active-badge">ใช้งานอยู่</span>}{!node.playable && <span className="future-badge">ยังไม่เปิดใน Test Build</span>}</article>)}</div></div>)}</section></div>}</main>;
}
